[phases.setup]
    aptPkgs = ["python3", "gcc"]

[phases.install]
    cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
    cmds = ["gunicorn --bind 0.0.0.0:5000 app:app"]
